spring:
  thymeleaf:
    cache: false
  datasource:
    username: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/AALMS
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org:
      springframework:
         web: DEBUG

